model:
  dimensions:
    obs_size: 1
    latent_size: 1  # same as observation
    hidden_size: 20
  observation:
    obs_model: identity
    clipped: false
    learn_noise_cov: false
  hierarchy:
    scheme: projection
    num_individual_params: 6
    lambda_regularization: 0.01

training:
  sequence:
    seq_len: 30  # 30 timepoints per segment (178 timepoints for each subject)
    train_set_size: 120
  optimization:
    num_epochs: 100
    batch_size: 320
    weight_decay: 0.0
    clip_grad_norm: 0.0
    num_workers: 2
    learning_rate:
      shared: 0.0001
      individual: 0.001
  teacher_forcing:
    alpha_start: 0.1
    alpha_end: 0.0

evaluation:
  metrics:
    enabled: [kl, pse, mse]
    kl_bins: 30
    pse_smooth: 15
  plots:
    enabled: []  # no plotting

runtime:
  compile: false
